// <auto-generated />
using System;
using ExamenU2_POO_ElkinBohorquez.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenU2_POO_ElkinBohorquez.Migrations
{
    [DbContext(typeof(ExamenDbContext))]
    [Migration("20250314232955_AddTableEmpleados")]
    partial class AddTableEmpleados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ExamenU2_POO_ElkinBohorquez.Database.Entities.EmpleadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_salary");

                    b.Property<DateTime>("DateContratation")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_contratation");

                    b.Property<string>("Departament")
                        .HasColumnType("TEXT")
                        .HasColumnName("departament");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("WorkStation")
                        .HasColumnType("TEXT")
                        .HasColumnName("work_station");

                    b.HasKey("Id");

                    b.ToTable("empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
