// <auto-generated />
using System;
using ExamenU2_POO_ElkinBohorquez.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenU2_POO_ElkinBohorquez.Migrations
{
    [DbContext(typeof(ExamenDbContext))]
    partial class ExamenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ExamenU2_POO_ElkinBohorquez.Database.Entities.DetallePlanillaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_salary");

                    b.Property<decimal>("Bonificaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("bonifications");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("coments");

                    b.Property<decimal>("Deducciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("deductions");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("empleado");

                    b.Property<decimal>("HorasExtras")
                        .HasColumnType("TEXT")
                        .HasColumnName("extra_hours");

                    b.Property<decimal>("MontoHorasExtra")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_extra_hours");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("planilla_id");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("TEXT")
                        .HasColumnName("net_salary");

                    b.HasKey("Id");

                    b.ToTable("detalle_planilla");
                });

            modelBuilder.Entity("ExamenU2_POO_ElkinBohorquez.Database.Entities.EmpleadoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_salary");

                    b.Property<DateTime>("DateContratation")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_contratation");

                    b.Property<string>("Departament")
                        .HasColumnType("TEXT")
                        .HasColumnName("departament");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("WorkStation")
                        .HasColumnType("TEXT")
                        .HasColumnName("work_station");

                    b.HasKey("Id");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("ExamenU2_POO_ElkinBohorquez.Database.Entities.PlanillaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_creation");

                    b.Property<DateTime>("DatePay")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_pay");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("periodo");

                    b.Property<string>("State")
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("planilla");
                });
#pragma warning restore 612, 618
        }
    }
}
